name: Sync Media Folder

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blog Repository
        uses: actions/checkout@v2
        with:
          repository: readandprogress/reading.is-a.dev
          path: blog-repo

      - name: Checkout Notes Repository
        uses: actions/checkout@v2
        with:
          repository: readandprogress/Notes
          path: notes-repo
          token: ${{ secrets.NOTES_REPO_TOKEN }}

      - name: Sync Media Folder
        run: |
          # Copy the Media folder itself to the _tabs directory
          cp -r notes-repo/Media blog-repo/_tabs/
          cd blog-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _tabs/Media
          git commit -m "Sync Media folder from notes repository" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/readandprogress/reading.is-a.dev.git HEAD:main
